# Generated by Django 5.2.3 on 2025-06-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_deleted', models.DateTimeField(null=True)),
                ('favicon', models.URLField(null=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('title', models.CharField(default='Smth', max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='main.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('time_deleted__isnull', True)), fields=('url',), name='URL_UNIQUE_IF_NOT_DELETED')],
            },
        ),
    ]
